version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/vlnrajesh/log-archiver
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
          name: "Create a temp direcory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            cd utils
            gotestsum --junitfile /tmp/artifacts/unit-tests.xml
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts
