# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/vlnrajesh/log-archiver
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
          name: "Create a temp direcory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            cd utils
            go test -coverprofile=cp.out
            go tool cover -html cp.out -o /tmp/artifacts/coverage.html
      - store_artifacts:
          path: /tmp/artifacts
